const columns = [
  {
    header: "Player's name",
    accessor: "Player",
    isFilterable: true,
    isSortable: false,
    width: 150,
    type: "string",
  },
  {
    header: "Player's team abbreviation",
    accessor: "Team",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "string",
  },
  {
    header: "Player's postion",
    accessor: "Pos",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "string",
  },
  {
    header: "Rushing Attempts Per Game Average",
    accessor: "Att/G",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
  {
    header: "Rushing Attempts",
    accessor: "Att",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
  {
    header: "Total Rushing Yards",
    accessor: "Yds",
    isFilterable: false,
    isSortable: true,
    width: 150,
    type: "number",
  },
  {
    header: "Rushing Average Yards Per Attempt",
    accessor: "Avg",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
  {
    header: "Rushing Yards Per Game",
    accessor: "Yds/G",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
  {
    header: "Total Rushing Touchdowns",
    accessor: "TD",
    isFilterable: false,
    isSortable: true,
    width: 150,
    type: "number",
  },
  {
    header: "Longest Rush",
    accessor: "Lng",
    isFilterable: false,
    isSortable: true,
    width: 150,
    type: "number",
  },
  {
    header: "Rushing First Downs",
    accessor: "1st",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
  {
    header: "Rushing First Down Percentage",
    accessor: "1st%",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
  {
    header: "Rushing 20+ Yards Each",
    accessor: "20+",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
  {
    header: "Rushing 40+ Yards Each",
    accessor: "40+",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
  {
    header: "Rushing Fumbles",
    accessor: "FUM",
    isFilterable: false,
    isSortable: false,
    width: 150,
    type: "number",
  },
];

export { columns };
